environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - ./build.cmd

cache:
  - node_modules -> npm-shrinkwrap.json, package.json

test: off
